### PR TITLE
alsoFetch: (a ToManyRelation) now also resolves the collection proxy

### PR DESCRIPTION
**Pull request by ironirc**
As requested by astares, a new PR.
I just applied the code, without any further testing.

### CODE REVIEW

**Comment by astares** [comment]
For the records: this is a substitute for https://github.com/pharo-rdbms/glorp/pull/8

and now checks have passed without merge conflict. 

But having a better description and a tests for the actual situation that it solves would be a plus and a safe way forward. 
Would that be possible to provide?

**Comment by ironirc** [comment]
I found my original post on discord about this:  https://discord.com/channels/223421264751099906/300255715337961474/562960614536904709
This was the content of the original post:
Hi, I've got a question about Glorp "alsoFetch:"
example:
```
((SimpleQuery read: Invoice)
    alsoFetch: [:each | each invoiceLines asOuterJoin ]) executeIn: session.
```

For the invoices that don't have invoiceLines, the ToMany proxy invoiceLines doesn't get resolved.
Can someone confirm this?

**Comment by gcotelli** [comment]
I've run our own test suite against these changes and all tests are still passing. 
As @astares suggested it would be good to have a test case covering the case these changes are fixing. To not break inadvertently it in the future.

**Comment by ironirc** [comment]
Hi, I just added the test case.

**Comment by gcotelli** [comment]
Thank you @ironirc

**Pull request merged**
