### PR TITLE
Add Pharo 10 support

### PR DESCRIPTION
**Pull request by gcotelli**

### CODE REVIEW

**Comment by tblanchard** [comment]
Did we give up on point releases going from 9.0 to 10?

**Comment by gcotelli** [comment]
> Did we give up on point releases going from 9.0 to 10?

At least on smalltalkCI. For the previous Pharo versions, there wasn't anyways an option for point releases. So 9.0 will use the latest 9.0.x release available, but no way to use 9.0.0 once 9.0.1 was released.

**Comment by gcotelli** [comment]
@tblanchard all tests are now green. Can I use you as a reviewer?

**Review by tblanchard — COMMENTED** [review]
@gcotelli This looks great.  Thank you for making these improvements!  I will test locally later today and approve if I find no issues.

**Comment by gcotelli** [comment]
@tblanchard Did you have any chance to test the changes? I'm waiting on these changes to update other projects ;)

**Review by tblanchard — APPROVED** [review]
Looks good in Pharo 10

**Pull request merged**
